name: Run TestNG Daily

on:
  schedule:
    - cron: '0 9 * * *' # Chạy vào 09:00 AM UTC (tức 16:00 AM giờ Việt Nam)
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Dùng OpenJDK Temurin
          java-version: '17' # Chọn phiên bản Java phù hợp

      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Run TestNG Tests
        run: mvn test -DsuiteXmlFile=core.xml

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/
